import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */


 export const products = [
  //Best Feature
  {
    id: uuid(),
    title: "OnePlus Nord CE 5G",
    description: "Fast and reliable 5G smartphone with stunning display",
    price: 399,
    original_price: 450,
    discountPercentage: 12,
    rating: 4.5,
    inStock: true,
    brand: "OnePlus",
    category: "Smartphone",
    image: "https://tse1.mm.bing.net/th?id=OIP.5_2uU83seT7lKchCoom0zgHaEK&pid=Api&P=0",
    quantity: 1,
    trending: true,
    feature:"best"
  },
  {
    id: uuid(),
    title: "Asus ROG Zephyrus S17",
    description: "A high-end gaming laptop with advanced features from Asus",
    price: 2799,
    original_price: 3000,
    discountPercentage: 12.1,
    rating: 4.9,
    inStock: true,
    brand: "Asus",
    category: "Laptop",
    image: "https://tse3.mm.bing.net/th?id=OIP.-_jPyAwruttOWut2FDjYGgHaFG&pid=Api&P=0",
    quantity: 1,
    trending: true,
    feature:"best"
  },
  {
    id: uuid(),
    title: "LG 55 inch 4K UHD Smart TV",
    description: "Immersive viewing experience with vivid colors and deep contrast",
    price: 899,
    original_price: 999,
    discountPercentage: 15,
    rating: 4.7,
    inStock: true,
    brand: "LG",
    category: "Television",
    image: "https://tse3.mm.bing.net/th?id=OIP.p67Ii19ZVd6TsTSB36kgQgHaE6&pid=Api&P=0",
    quantity: 1,
    trending: true,
    feature:"best",
  },
  {
    id: uuid(),
    title: "Sennheiser HD 660 S",
    description: "High-end open-back headphones for audiophiles from Sennheiser",
    price: 499,
    original_price: 599,
    discountPercentage: 10,
    rating: 4.7,
    inStock: true,
    brand: "Sennheiser",
    category : "Headphone",
    image: "https://tse1.mm.bing.net/th?id=OIP.l0H5yurqu1f-jtaUjfSgxQHaE8&pid=Api&P=0",
    quantity: 1,
    trending: true,
    feature:"best",
  },


  // Product List
  {
    id: uuid(),
    title: "Samsung Galaxy S21",
    description: "The Samsung Galaxy S21 is a powerful and stylish smartphone.",
    price: 799,
    original_price: 899,
    discountPercentage: 10,
    rating: 4.8,
    inStock: true,
    brand: "Samsung",
    category: "Smartphone",
    image: "https://tse4.mm.bing.net/th?id=OIP.3iRYOSf6W5lk-EcweYMnAwHaHY&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Dell XPS 13",
    description: "The Dell XPS 13 is a powerful and portable laptop for work or play.",
    price: 1299,
    original_price: 1450,
    discountPercentage: 5,
    rating: 4.5,
    inStock: true,
    brand: "Dell",
    category: "Laptop",
    image: "https://tse2.mm.bing.net/th?id=OIP.unbf-0rI0E7vvl0CpBbZRgHaHa&pid=Api&P=0",
    quantity: 1,
    trending: false,
  },
  {
    id: uuid(),
    title: "LG CX 55-inch OLED TV",
    description: "The LG CX 55-inch OLED TV delivers stunning picture quality with deep blacks and vibrant colors.",
    price: 1599,
    original_price: 1899,
    discountPercentage: 15,
    rating: 4.9,
    inStock: true,
    brand: "LG",
    category: "Television",
    image: "https://tse2.mm.bing.net/th?id=OIP.vuoEdJTao0XR3qqMaIgZjQHaFU&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Bose SoundLink Revolve",
    description: "The Bose SoundLink Revolve is a portable Bluetooth speaker with 360-degree sound.",
    price: 199,
    original_price: 250,
    discountPercentage: 10,
    rating: 4.6,
    inStock: false,
    brand: "Bose",
    category: "Speaker",
    image: "https://tse3.mm.bing.net/th?id=OIP.X2QiQOaqZFSqVUV5aMbcvQAAAA&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Sony WH-1000XM4",
    description: "The Sony WH-1000XM4 are premium noise-cancelling headphones with excellent sound quality.",
    price: 349,
    original_price: 400,
    discountPercentage: 20,
    rating: 4.7,
    inStock: true,
    brand: "Sony",
    category: "Headphone",
    image: "https://tse2.mm.bing.net/th?id=OIP.gfnCgN3yE98n9xlUYQbT5AHaE8&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Samsung Galaxy S20",
    description: "A high-end smartphone with 5G support",
    price: 799,
    original_price: 999,
    discountPercentage: 10,
    rating: 4.5,
    inStock: true,
    brand: "Samsung",
    category: "Smartphone",
    image: "https://tse1.mm.bing.net/th?id=OIP.qUEkzvgxjQC72s6JwSnGrwHaDt&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Dell XPS 13",
    description: "A high-performance laptop with an InfinityEdge display",
    price: 1299,
    original_price: 1500,
    discountPercentage: 15,
    rating: 4.8,
    inStock: true,
    brand: "Dell",
    category: "Laptop",
    image: "https://tse2.mm.bing.net/th?id=OIP.unbf-0rI0E7vvl0CpBbZRgHaHa&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "LG CX Series 4K OLED TV",
    description: "A stunning OLED TV with HDMI 2.1 and G-Sync support",
    price: 1799,
    original_price: 2000,
    discountPercentage: 20,
    rating: 4.9,
    inStock: true,
    brand: "LG",
    category: "Television",
    image: "https://tse3.mm.bing.net/th?id=OIP.cm56LYy8pbKy-TaxZlMTQAHaEj&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Bose SoundLink Revolve+",
    description: "A powerful Bluetooth speaker with 360-degree sound",
    price: 299,
    original_price: 300,
    discountPercentage: 5,
    rating: 4.7,
    inStock: true,
    brand: "Bose",
    category: "Speaker",
    image: "https://tse3.mm.bing.net/th?id=OIP.X2QiQOaqZFSqVUV5aMbcvQAAAA&pid=Api&P=0",
    quantity: 1,
    trending: false,
  },
  {
    id: uuid(),
    title: "Sony WH-1000XM4",
    description: "Premium noise-cancelling headphones with long battery life",
    price: 349,
    original_price: 599,
    discountPercentage: 10,
    rating: 4.9,
    inStock: true,
    brand: "Sony",
    category: "Headphone",
    image: "https://tse2.mm.bing.net/th?id=OIP.gfnCgN3yE98n9xlUYQbT5AHaE8&pid=Api&P=0",
    quantity: 1,
    trending: true
  },{
    id: uuid(),
    title: "Dell Inspiron 15 5000",
    description: "A powerful laptop for work and play",
    price: 799,
    original_price:899,
    discountPercentage: 10,
    rating: 4.5,
    inStock: true,
    brand: "Dell",
    category: "Laptop",
    image: "https://tse4.mm.bing.net/th?id=OIP.q4BX9OeXPfwTTEDm-faivgHaHa&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "LG 55 inch 4K UHD Smart TV",
    description: "Immersive viewing experience with vivid colors and deep contrast",
    price: 899,
    original_price: 1100,
    discountPercentage: 15,
    rating: 4.7,
    inStock: true,
    brand: "LG",
    category: "Television",
    image: "https://tse3.mm.bing.net/th?id=OIP.p67Ii19ZVd6TsTSB36kgQgHaE6&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Bose QuietComfort 35 II",
    description: "Wireless noise-cancelling headphones for a truly immersive experience",
    price: 299,
    original_price: 499,
    discountPercentage: 5,
    rating: 4.8,
    inStock: true,
    brand: "Bose",
    category: "Headphone",
    image: "https://tse4.mm.bing.net/th?id=OIP.hsFJ-FY3zm2zdgejV5AmTAHaFY&pid=Api&P=0",
    quantity: 1,
    trending: false,
  },
  {
    id: uuid(),
    title: "JBL Flip 5 Waterproof Portable Bluetooth Speaker",
    description: "Powerful and portable speaker with waterproof design",
    price: 119,
    original_price: 350,
    discountPercentage: 8,
    rating: 4.4,
    inStock: true,
    brand: "JBL",
    category: "Speaker",
    image: "https://tse1.mm.bing.net/th?id=OIP.3eZ05ZpVkO7tKYhRIa8EvAHaHa&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "OnePlus Nord CE 5G",
    description: "Fast and reliable 5G smartphone with stunning display",
    price: 399,
    original_price: 499,
    discountPercentage: 12,
    rating: 4.5,
    inStock: true,
    brand: "OnePlus",
    category: "Smartphone",
    image: "https://tse1.mm.bing.net/th?id=OIP.5_2uU83seT7lKchCoom0zgHaEK&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Samsung Galaxy Tab S7",
    description: "Powerful tablet with stunning display and S Pen included",
    price: 649,
    original_price: 899,
    discountPercentage: 10,
    rating: 4.6,
    inStock: true,
    brand: "Samsung",
    category: "Tablet",
    image: "https://tse3.mm.bing.net/th?id=OIP.SvWqMUNLJkrcGBn2LhQvkQHaGk&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "HP Spectre x360",
    description: "A premium 2-in-1 laptop with a sleek design and powerful performance",
    price: 1499,
    original_price: 1899,
    discountPercentage: 8,
    rating: 4.8,
    inStock: true,
    brand: "HP",
    category: "Laptop",
    image: "https://tse3.mm.bing.net/th?id=OIP.p7i_DnK7tqXL08DO0cRomgHaFj&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "LG OLED55C1PUB",
    description: "A high-end 55-inch OLED TV with stunning picture quality and smart features",
    price: 1999,
    original_price: 2599,
    discountPercentage: 15,
    rating: 4.9,
    inStock: true,
    brand: "LG",
    category: "Television",
    image: "https://tse1.mm.bing.net/th?id=OIP.ewh-IuQiNIjRxp2a-D8p3gHaHa&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Bose QuietComfort 35 II",
    description: "Premium noise-cancelling headphones with superb sound quality and comfort",
    price: 349,
    original_price: 459,
    discountPercentage: 10,
    rating: 4.7,
    inStock: true,
    brand: "Bose",
    category : "Headphone",
    image: "https://tse4.mm.bing.net/th?id=OIP.hsFJ-FY3zm2zdgejV5AmTAHaFY&pid=Api&P=0",
    quantity: 1,
    trending: true
  },
  {
    id: uuid(),
    title: "Sonos One (Gen 2)",
    description: "A smart speaker with great sound and voice control for your home",
    price: 199,
    original_price: 259,
    discountPercentage: 5,
    rating: 4.5,
    inStock: true,
    brand: "Sonos",
    category: "Speaker",
    image: "https://tse3.mm.bing.net/th?id=OIP.jou46qIRkv_zyJd_vF4UZgHaHa&pid=Api&P=0",
    quantity: 1,
    trending: false,
  },
  {
    id: uuid(),
    title: "Sony WH-1000XM4",
    description: "Industry leading wireless noise cancelling headphones",
    price: 349,
    original_price: 499,
    discountPercentage :18,
    rating: 4.8,
    inStock : true,
    brand: "Sony",
    category : "Headphone",
    image: "https://tse2.mm.bing.net/th?id=OIP.TVnToERTo6OvGSRzlWnugAHaFX&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
  {
    id: uuid(),
    title: "LG 65UN7300PUF",
    description: "65 inch 4K Ultra HD Smart LED TV",
    price: 799,
    original_price: 999,
    discountPercentage : 8,
    rating: 4.5,
    inStock : true,
    brand: "LG",
    category : "Television",
    image: "https://tse1.mm.bing.net/th?id=OIP._fwhtRXzJa8u4W5N7kaPnQHaE6&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
  {
    id: uuid(),
    title: "Dell XPS 13",
    description: "13.3 inch 4K Ultra HD Touchscreen Laptop",
    price: 1399,
    original_price: 1599,
    discountPercentage : 10,
    rating: 4.7,
    inStock : true,
    brand: "Dell",
    category: "Laptop",
    image: "https://tse2.mm.bing.net/th?id=OIP.unbf-0rI0E7vvl0CpBbZRgHaHa&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
  {
    id: uuid(),
    title: "JBL Flip 5",
    description: "Portable Waterproof Bluetooth Speaker",
    price: 119,
    original_price: 399,
    discountPercentage : 5,
    rating: 4.5,
    inStock : true,
    brand: "JBL",
    category : "Speaker",
    image: "https://tse1.mm.bing.net/th?id=OIP.4xdW8j8UUydtyzbNZQTvSgHaHa&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
  {
    id: uuid(),
    title: "Bose QuietComfort 35 II Wireless Headphones",
    description: "Wireless headphones with noise cancelling technology",
    price: 299,
    original_price: 489,
    discountPercentage : 10,
    rating: 4.8,
    inStock : false,
    brand: "Bose",
    category : "Headphone",
    image: "https://tse4.mm.bing.net/th?id=OIP.hsFJ-FY3zm2zdgejV5AmTAHaFY&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
  {
    id: uuid(),
    title: "Samsung 75\" Class Q90T QLED 4K UHD HDR Smart TV",
    description: "75 inch 4K UHD HDR Smart TV with Quantum Processor 4K",
    price: 3999,
    original_price: 5999,
    discountPercentage : 15,
    rating: 4.9,
    inStock : true,
    brand: "Samsung",
    category : "Television",
    image: "https://tse3.mm.bing.net/th?id=OIP.pPSOt3eH7u44w9bIdDDlWwHaEK&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
  {
    id: uuid(),
    title: "Lenovo ThinkPad X1 Carbon Gen 9",
    description: "14 inch business laptop with Intel Core i7 processor",
    price: 1849,
    original_price: 2599,
    discountPercentage : 8,
    rating: 4.7,
    inStock : true,
    brand: "Lenovo",
    category: "Laptop",
    image: "https://tse3.mm.bing.net/th?id=OIP.ufYDmDtilN86d9M_QqigAwHaFj&pid=Api&P=0",
    quantity : 1,
    trending : true
  },
    {
      id: uuid(),
      title: "Apple MacBook Pro",
      description: "Powerful laptop with a stunning display",
      price: 1299,
      original_price: 1899,
      discountPercentage: 10,
      rating: 4.8,
      inStock: true,
      brand: "Apple",
      category: "Laptop",
      image: "https://tse4.mm.bing.net/th?id=OIP.1Tmm-aMTgClsZU2km4NxfQHaE8&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Bose QuietComfort 35 II",
      description: "Wireless noise-cancelling headphones",
      price: 299,
      original_price: 499,
      discountPercentage: 8,
      rating: 4.5,
      inStock: true,
      brand: "Bose",
      category: "Headphone",
      image: "https://tse4.mm.bing.net/th?id=OIP.hsFJ-FY3zm2zdgejV5AmTAHaFY&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Sony BRAVIA XBR",
      description: "4K HDR television with built-in Google Assistant",
      price: 1399,
      original_price: 1999,
      discountPercentage: 20,
      rating: 4.9,
      inStock: true,
      brand: "Sony",
      category: "Television",
      image: "https://tse2.mm.bing.net/th?id=OIP.sIWJPt7FxBRKvTzHWbWRnAHaFj&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Google Nest Audio",
      description: "Smart speaker with powerful sound",
      price: 99,
      original_price: 199,
      discountPercentage: 50,
      rating: 4.6,
      inStock: true,
      brand: "Google",
      category: "Speaker",
      image: "https://tse3.mm.bing.net/th?id=OIP.qxgQWAOX9gLazZ3VHQ0FvwHaF7&pid=Api&P=0",
      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Dell Inspiron 15",
      description: "Affordable laptop with decent specs",
      price: 599,
      original_price: 899,
      discountPercentage: 12,
      rating: 4.2,
      inStock: false,
      brand: "Dell",
      category: "Laptop",
      image: "https://tse3.mm.bing.net/th?id=OIP.Q0c_UwBDsHGu_lfFflKFkAHaHa&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Samsung Galaxy Buds Pro",
      description: "Wireless earbuds with great sound quality",
      price: 199,
      original_price: 259,
      discountPercentage: 7,
      rating: 4.4,
      inStock: true,
      brand: "Samsung",
      category: "Headphone",
      image: "https://tse4.mm.bing.net/th?id=OIP.oCkT99j3aaQabe4zncRgrgHaFj&pid=Api&P=0",
      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Dell XPS 13",
      description: "A sleek and powerful laptop from Dell",
      price: 1199,
      original_price: 2199,
      discountPercentage: 8,
      rating: 4.8,
      inStock: true,
      brand: "Dell",
      category: "Laptop",
      image: "https://tse2.mm.bing.net/th?id=OIP.unbf-0rI0E7vvl0CpBbZRgHaHa&pid=Api&P=0",
      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Sony BRAVIA X8000H",
      description: "A 4K smart TV with incredible picture quality from Sony",
      price: 849,
      original_price: 1199,
      discountPercentage: 10,
      rating: 4.5,
      inStock: true,
      brand: "Sony",
      category: "Television",
      image: "https://tse1.mm.bing.net/th?id=OIP.BxjunoH7PKg2Y_9KfPvQ2QHaEK&pid=Api&P=0",
      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Bose SoundLink Revolve",
      description: "A portable Bluetooth speaker with 360 degree sound from Bose",
      price: 199,
      original_price: 259,
      discountPercentage: 5,
      rating: 4.4,
      inStock :false,
      brand: "Bose",
      category: "Speaker",
      image: "https://tse3.mm.bing.net/th?id=OIP.X2QiQOaqZFSqVUV5aMbcvQAAAA&pid=Api&P=0",

      quantity:false,
      trending: true
    },
    {
      id: uuid(),
      title: "Sennheiser HD 660 S",
      description: "High-end open-back headphones for audiophiles from Sennheiser",
      price: 499,
      original_price: 799,
      discountPercentage: 10,
      rating: 4.7,
      inStock: true,
      brand: "Sennheiser",
      category : "Headphone",
      image: "https://tse1.mm.bing.net/th?id=OIP.l0H5yurqu1f-jtaUjfSgxQHaE8&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Samsung Galaxy A52",
      description: "A mid-range smartphone from Samsung with great camera features",
      price: 349,
      original_price: 499,
      discountPercentage: 7,
      rating: 4.3,
      inStock: true,
      brand: "Samsung",
      category: "Smartphone",
      image: "https://tse2.mm.bing.net/th?id=OIP.KAF37TJSmM06YuNGM7SRMQHaHa&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Asus ROG Zephyrus S17",
      description: "A high-end gaming laptop with advanced features from Asus",
      price: 2799,
      original_price: 4999,
      discountPercentage: 12,
      rating: 4.9,
      inStock: true,
      brand: "Asus",
      category: "Laptop",
      image: "https://tse3.mm.bing.net/th?id=OIP.-_jPyAwruttOWut2FDjYGgHaFG&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Apple MacBook Air",
      description: "A thin and light laptop with impressive performance",
      price: 1199,
      original_price: 1899,
      discountPercentage: 10,
      rating: 4.7,
      inStock: true,
      brand: "Apple",
      category: "Laptop",
      image: "https://tse2.explicit.bing.net/th?id=OIP.8RNPKuSjnWn7bfwInPy3WAHaHa&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "LG 65-Inch 4K Ultra HD Smart LED TV",
      description: "A large, high-quality TV with smart features",
      price: 999,
      original_price: 1599,
      discountPercentage: 15,
      rating: 4.5,
      inStock: true,
      brand: "LG",
      category: "Television",
      image: "https://tse1.mm.bing.net/th?id=OIP.2Hht5ZNCH3FbCpPFyiY4zAHaHa&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Bose SoundLink Mini II",
      description: "A portable Bluetooth speaker with excellent sound",
      price: 199,
      original_price: 399,
      discountPercentage: 8,
      rating: 4.9,
      inStock: true,
      brand: "Bose",
      category: "Speaker",
      image: "https://tse3.mm.bing.net/th?id=OIP.7cUSp0IzXfbsDWPhYdrVWgHaHa&pid=Api&P=0",

      quantity: 1,
      trending: false
    },
    {
      id: uuid(),
      title: "Sony WH-1000XM4 Wireless Noise-Canceling Headphones",
      description: "High-quality wireless headphones with noise cancellation",
      price: 349,
      original_price: 599,
      discountPercentage: 12,
      rating: 4.8,
      inStock: true,
      brand: "Sony",
      category : "Headphone",
      image: "https://tse2.mm.bing.net/th?id=OIP.TVnToERTo6OvGSRzlWnugAHaFX&pid=Api&P=0",

      quantity: 1,
      trending: true
    },
    {
      id: uuid(),
      title: "Google Pixel 5",
      description: "A high-performance smartphone with a great camera",
      price: 799,
      original_price: 999,
      discountPercentage: 10,
      rating: 4.7,
      inStock: true,
      brand: "Google",
      category: "Smartphone",
      image: "https://tse1.mm.bing.net/th?id=OIP.VBZto4L811G9f0vNvK9whgHaFj&pid=Api&P=0",

      quantity: 1,
      trending: true
    },

];


// smartphones: 5,
// laptop: 11,
// television: 9,
// speaker: 8,
// headphones: 10,
// tablets: 1
