export const initialState = {
  products: [],
  category: [],
  wishlist: [],
  productDetail: {},
  cart: [],
  brands: [],
  filters: {
    rating: 5,
    category: [],
    brand: [],
    price: null,
    trending: false,
    includeOutStock: false,
    arrangeType: "",
    reqPage: 1,
    searchText: "",
  },
  loader2: false,
  searchLoader: true,
  searchValue: "",
  searchedProducts: [],
  showBurger: false,
  showSearch: false,
  currentPage: 1,
  screenWidth: window.innerWidth,
  showPassword: false,
  showFilter: false,
  showSignUpPassword: false,
  showSearchedProducts: false,
  addressList: [
    {
      id: "2354drtgf4d-7555-49cb--4b09711yujd",
      name: "Donald Modi",
      address: "194 america main road near San Francisco",
      city: "Indore",
      mobile: 9302101111,
      alternatemobile: 123456789,
      pincode: "99988",
      state: "Moscow Pradesh",
      type: "Home",
    },
  ],
  showAddressModal: false,
  selectedAddress: "2354drtgf4d-7555-49cb--4b09711yujd",
  editId: "",
  orderDetails: [],
};
