export const initialState = {
    products: [],
    category: [],
    wishlist: [],
    cart: [],
    filters: {
      rating: 5,
      categoryFilter: [],
      brandFilter: [],
      price: null,
      trending: false,
      includeOutStock: false,
      arrangeType: "",
    },
    searchValue: "",
    searchedProducts: [],
    showBurger: false,
    showSearch: false,
    currentPage: 1,
    screenWidth: window.innerWidth,
    showPassword: false,
    showFilter: false,
    showSignUpPassword: false,
    showSearchedProducts: false,
    addressList: [
      {
        id: "2354drtgf4d-7555-49cb--4b09711yujd",
        name: "Donald Modi",
        address: "194 america main road near San Francisco",
        city: "Indore",
        mobile: 9302101111,
        alternatemobile: 123456789,
        pincode: "99988",
        state: "Moscow Pradesh",
      },
    ],
    showAddressModal: false,
    selectedAddress: "2354drtgf4d-7555-49cb--4b09711yujd",
    orderDetails:[]
  };